modLoader="javafml"
loaderVersion="[36,)"

license="MIT"
issueTrackerURL="https://github.com/Hellish-Mods/digitalityAPI/issues"

[[mods]]
modId="digitality"
version="${file.jarVersion}"

displayName="digitalityAPI"
displayURL="https://www.curseforge.com/minecraft/mc-mods/digitalityAPI"
logoFile="pack.png"

authors="Hellish Mods & Modern Modpacks"
credits="""
G_cat (Coding)
"""

description="A small library that makes it easy to add resource files at runtime with code."

[[dependencies.digitality]]
    modId="forge"
    mandatory=true

    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.digitality]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"